# Matrices: inversa y factorizaciones.

**Objetivo.** Revisar e ilustrar los conceptos de la matriz inversa y algunas factorizaciones usando las bibliotecas `sympy` y `numpy`.

 <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/"><a property="dct:title" rel="cc:attributionURL" href="https://github.com/repomacti/macti/tree/main/notebooks/Algebra_Lineal_01">MACTI-Algebra_Lineal_01</a> by <a rel="cc:attributionURL dct:creator" property="cc:attributionName" href="https://www.macti.unam.mx">Luis M. de la Cruz</a> is licensed under <a href="http://creativecommons.org/licenses/by-sa/4.0/?ref=chooser-v1" target="_blank" rel="license noopener noreferrer" style="display:inline-block;">Attribution-ShareAlike 4.0 International<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/sa.svg?ref=chooser-v1"></a></p> 

**Trabajo realizado con el apoyo del Programa UNAM-DGAPA-PAPIME, proyectos PE101019 y PE101922.**

### Inversa

$$
\left[
\begin{array}{ccc}
1 & 2 & 3 \\
3 & 6 & 2 \\
2 & 0 & 1
\end{array}
\right] 
\left[ 
\begin{array}{c}
x \\ y \\ z 
\end{array}
\right]
= 
\left[ 
\begin{array}{c}
1 \\ 2 \\ 3 
\end{array}
\right]
$$

In [1]:
import numpy as np
import sympy

In [2]:
M = sympy.Matrix([[1, 2, 3], [3, 6, 2], [2, 0, 1]])
M

Matrix([
[1, 2, 3],
[3, 6, 2],
[2, 0, 1]])

In [3]:
MI = M.inv()
MI

Matrix([
[-3/14, 1/14,  1/2],
[-1/28, 5/28, -1/4],
[  3/7, -1/7,    0]])

In [4]:
M * MI

Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]])

In [5]:
b = sympy.Matrix([1, 2, 3])
b

Matrix([
[1],
[2],
[3]])

In [6]:
sol = MI * b 
sol

Matrix([
[10/7],
[-3/7],
[ 1/7]])

In [7]:
M * sol

Matrix([
[1],
[2],
[3]])

### Descomposición LU

In [8]:
L, U, perm = M.LUdecomposition()
L

Matrix([
[1, 0, 0],
[2, 1, 0],
[3, 0, 1]])

In [9]:
U

Matrix([
[1,  2,  3],
[0, -4, -5],
[0,  0, -7]])

In [10]:
perm

[[1, 2]]

In [11]:
L * U

Matrix([
[1, 2, 3],
[2, 0, 1],
[3, 6, 2]])

In [12]:
M

Matrix([
[1, 2, 3],
[3, 6, 2],
[2, 0, 1]])

In [13]:
b

Matrix([
[1],
[2],
[3]])

In [14]:
sol_LU = M.LUsolve(b)
sol_LU

Matrix([
[10/7],
[-3/7],
[ 1/7]])

In [15]:
M * sol_LU

Matrix([
[1],
[2],
[3]])

In [32]:
from scipy.linalg import lu

M_np = np.array(M).astype(np.float64)

In [33]:
p, l, u = lu(M_np)

In [34]:
p

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [35]:
l

array([[ 1.        ,  0.        ,  0.        ],
       [ 0.66666667,  1.        ,  0.        ],
       [ 0.33333333, -0.        ,  1.        ]])

In [36]:
u

array([[ 3.        ,  6.        ,  2.        ],
       [ 0.        , -4.        , -0.33333333],
       [ 0.        ,  0.        ,  2.33333333]])

In [37]:
l @ u

array([[3., 6., 2.],
       [2., 0., 1.],
       [1., 2., 3.]])

### Descomposición QR

In [17]:
Q, R = M.QRdecomposition()

In [18]:
Q

Matrix([
[  sqrt(14)/14,   sqrt(35)/35, 3*sqrt(10)/10],
[3*sqrt(14)/14, 3*sqrt(35)/35,  -sqrt(10)/10],
[   sqrt(14)/7,   -sqrt(35)/7,             0]])

In [19]:
R

Matrix([
[sqrt(14), 10*sqrt(14)/7, 11*sqrt(14)/14],
[       0,  4*sqrt(35)/7,  4*sqrt(35)/35],
[       0,             0,  7*sqrt(10)/10]])

In [20]:
Q * R

Matrix([
[1, 2, 3],
[3, 6, 2],
[2, 0, 1]])

In [21]:
q, r = np.linalg.qr(M)

In [22]:
q

array([[-2.67261242e-01, -1.69030851e-01, -9.48683298e-01],
       [-8.01783726e-01, -5.07092553e-01,  3.16227766e-01],
       [-5.34522484e-01,  8.45154255e-01, -6.66133815e-16]])

In [23]:
r

array([[-3.74165739, -5.34522484, -2.93987366],
       [ 0.        , -3.38061702, -0.6761234 ],
       [ 0.        ,  0.        , -2.21359436]])

In [24]:
q @ r

array([[1., 2., 3.],
       [3., 6., 2.],
       [2., 0., 1.]])

### Descomposición de Cholesky

In [39]:
C = np.array([[6, 3, 4, 8], [3, 6, 5, 1], [4, 5, 10, 7], [8, 1, 7, 25]])

In [40]:
L = np.linalg.cholesky(C)

In [41]:
L

array([[ 2.44948974,  0.        ,  0.        ,  0.        ],
       [ 1.22474487,  2.12132034,  0.        ,  0.        ],
       [ 1.63299316,  1.41421356,  2.30940108,  0.        ],
       [ 3.26598632, -1.41421356,  1.58771324,  3.13249102]])

In [43]:
L.T

array([[ 2.44948974,  1.22474487,  1.63299316,  3.26598632],
       [ 0.        ,  2.12132034,  1.41421356, -1.41421356],
       [ 0.        ,  0.        ,  2.30940108,  1.58771324],
       [ 0.        ,  0.        ,  0.        ,  3.13249102]])

In [42]:
L @ L.T

array([[ 6.,  3.,  4.,  8.],
       [ 3.,  6.,  5.,  1.],
       [ 4.,  5., 10.,  7.],
       [ 8.,  1.,  7., 25.]])